search:
  projects:
    accession: accession
    title: title
    additional_attributes: additionalAttributes
    project_description: projectDescription
    sample_processing_protocol: sampleProcessingProtocol
    data_processing_protocol: dataProcessingProtocol
    project_tags: projectTags
    keywords: keywords
    doi: doi
    submission_type: submissionType
    license: license
    submission_date: submissionDate
    publication_date: publicationDate
    submitters: submitters
    lab_pis: labPIs
    instruments: instruments
    softwares: softwares
    experiment_types: experimentTypes
    quantification_methods: quantificationMethods
    countries: countries
    sample_attributes: sampleAttributes
    organisms: organisms
    organism_parts: organismParts
    diseases: diseases
    references: references
    identified_ptm_strings: identifiedPTMStrings
    total_file_downloads: totalFileDownloads
projects:
  default:
    accession: accession
    title: title
    additional_attributes: additionalAttributes
    project_description: projectDescription
    sample_processing_protocol: sampleProcessingProtocol
    data_processing_protocol: dataProcessingProtocol
    project_tags: projectTags
    keywords: keywords
    doi: doi
    submission_type: submissionType
    license: license
    submission_date: submissionDate
    publication_date: publicationDate
    submitters: submitters
    lab_pis: labPIs
    instruments: instruments
    softwares: softwares
    experiment_types: experimentTypes
    quantification_methods: quantificationMethods
    countries: countries
    sample_attributes: sampleAttributes
    organisms: organisms
    organism_parts: organismParts
    diseases: diseases
    references: references
    identified_ptm_strings: identifiedPTMStrings
    total_file_downloads: totalFileDownloads
  similarProjects:
    accession: accession
    affiliations: affiliations
    avg_wonloads_per_file: avgDownloadsPerFile
    data_processing_protocol: dataProcessingProtocol
    diseases: diseases
    doi: doi
    download_count: downloadCount
    experiment_types: experimentTypes
    instruments: instruments
    keywords: keywords
    lab_pis: labPIs
    organisms: organisms
    organisms_part: organismsPart
    other_omics_links: otherOmicsLinks
    percentile: percentile
    project_description: projectDescription
    project_file_names: projectFileNames
    project_tags: projectTags
    publication_date: publicationDate
    quantification_methods: quantificationMethods
    references: references
    sample_attributes: sampleAttributes
    sample_processing_protocol: sampleProcessingProtocol
    sdrf: sdrf
    softwares: softwares
    submission_date: submissionDate
    submission_type: submissionType
    submitters: submitters
    title: title
    updated_date: updatedDate
    yearly_downloads: yearlyDownloads