name: bioseqdownloader
channels:
  - bioconda
  - defaults
dependencies:
  - blast
  - pip:
    - pandas
    - tqdm
    - requests
    - rcsb-api
    - biopython
    - zeep
    - dotenv
    - pyyaml
    - beautifulsoup4