getpathways:
  name: Name
  title: Title
  description: Description
  source_database: Source_Database
db2db:
  affy_id: Affy ID
  agilent_id: Agilent ID
  allergome_code: Allergome Code
  apidb_cryptodb_id: ApiDB_CryptoDB ID
  biocarta_pathway_name: Biocarta Pathway Name
  biocyc_id: BioCyc ID
  ccds_id: CCDS ID
  chromosomal_location: Chromosomal Location
  cleanex_id: CleanEx ID
  codelink_id: CodeLink ID
  cosmic_id: COSMIC ID
  cpdb_protein_interactor: CPDB Protein Interactor
  ctd_disease_info: CTD Disease Info
  ctd_disease_name: CTD Disease Name
  cygd_id: CYGD ID
  dbsnp_id: dbSNP ID
  dictybase_id: dictyBase ID
  dip_id: DIP ID
  disprot_id: DisProt ID
  drugbank_drug_id: DrugBank Drug ID
  drugbank_drug_info: DrugBank Drug Info
  drugbank_drug_name: DrugBank Drug Name
  ec_number: EC Number
  echobase_id: EchoBASE ID
  ecogene_id: EcoGene ID
  ensembl_biotype: Ensembl Biotype
  ensembl_gene_id: Ensembl Gene ID
  ensembl_gene_info: Ensembl Gene Info
  ensembl_protein_id: Ensembl Protein ID
  ensembl_transcript_id: Ensembl Transcript ID
  flybase_gene_id: FlyBase Gene ID
  flybase_protein_id: FlyBase Protein ID
  flybase_transcript_id: FlyBase Transcript ID
  gad_disease_info: GAD Disease Info
  gad_disease_name: GAD Disease Name
  genbank_nucleotide_accession: GenBank Nucleotide Accession
  genbank_nucleotide_gi: GenBank Nucleotide GI
  genbank_protein_accession: GenBank Protein Accession
  genbank_protein_gi: GenBank Protein GI
  gene_id: Gene ID
  gene_info: Gene Info
  gene_symbol_and_synonyms: Gene Symbol and Synonyms
  gene_symbol_ordered_locus: Gene Symbol Ordered Locus
  gene_symbol_orf: Gene Symbol ORF
  gene_synonyms: Gene Synonyms
  genefarm_id: GeneFarm ID
  go_biological_process: GO - Biological Process
  go_cellular_component: GO - Cellular Component
  go_molecular_function: GO - Molecular Function
  go_id: GO ID
  gsea_standard_name: GSEA Standard Name
  h_inv_locus_id: H-Inv Locus ID
  hamap_id: HAMAP ID
  hgnc_id: HGNC ID
  hmdb_metabolite: HMDB Metabolite
  homolog_all_ens_gene_id: Homolog - All Ens Gene ID
  homolog_all_ens_protein_id: Homolog - All Ens Protein ID
  homolog_all_gene_id: Homolog - All Gene ID
  homolog_human_ens_gene_id: Homolog - Human Ens Gene ID
  homolog_human_ens_protein_id: Homolog - Human Ens Protein ID
  homolog_human_gene_id: Homolog - Human Gene ID
  homolog_mouse_ens_gene_id: Homolog - Mouse Ens Gene ID
  homolog_mouse_ens_protein_id: Homolog - Mouse Ens Protein ID
  homolog_mouse_gene_id: Homolog - Mouse Gene ID
  homolog_rat_ens_gene_id: Homolog - Rat Ens Gene ID
  homolog_rat_ens_protein_id: Homolog - Rat Ens Protein ID
  homolog_rat_gene_id: Homolog - Rat Gene ID
  homologene_id: HomoloGene ID
  hpa_id: HPA ID
  hprd_id: HPRD ID
  hprd_protein_complex: HPRD Protein Complex
  hprd_protein_interactor: HPRD Protein Interactor
  illumina_id: Illumina ID
  imgt_gene_db_id: IMGT/GENE-DB ID
  interpro_id: InterPro ID
  ipi_id: IPI ID
  kegg_disease_id: KEGG Disease ID
  kegg_gene_id: KEGG Gene ID
  kegg_orthology_id: KEGG Orthology ID
  kegg_pathway_id: KEGG Pathway ID
  kegg_pathway_info: KEGG Pathway Info
  kegg_pathway_title: KEGG Pathway Title
  legiolist_id: LegioList ID
  leproma_id: Leproma ID
  locus_tag: Locus Tag
  maizegdb_id: MaizeGDB ID
  merops_id: MEROPS ID
  mgc_zgc_xgc_id: MGC(ZGC/XGC) ID
  mgc_zgc_xgc_image_id: MGC(ZGC/XGC) Image ID
  mgc_zgc_xgc_info: MGC(ZGC/XGC) Info
  mgi_id: MGI ID
  mim_id: MIM ID
  mim_info: MIM Info
  mirbase_id: miRBase ID
  ncipid_pathway_name: NCIPID Pathway Name
  ncipid_protein_complex: NCIPID Protein Complex
  ncipid_protein_interactor: NCIPID Protein Interactor
  ncipid_ptm: NCIPID PTM
  orphanet_id: Orphanet ID
  panther_id: PANTHER ID
  paralog_ens_gene_id: Paralog - Ens Gene ID
  pbr_id: PBR ID
  pdb_id: PDB ID
  peroxibase_id: PeroxiBase ID
  pfam_id: Pfam ID
  pharmgkb_drug_info: PharmGKB Drug Info
  pharmgkb_gene_id: PharmGKB Gene ID
  pir_id: PIR ID
  pirsf_id: PIRSF ID
  pptasedb_id: PptaseDB ID
  prints_id: PRINTS ID
  prodom_id: ProDom ID
  prosite_id: PROSITE ID
  pseudocap_id: PseudoCAP ID
  pubmed_id: PubMed ID
  reactome_id: Reactome ID
  reactome_pathway_name: Reactome Pathway Name
  rebase_id: REBASE ID
  refseq_genomic_accession: RefSeq Genomic Accession
  refseq_genomic_gi: RefSeq Genomic GI
  refseq_mrna_accession: RefSeq mRNA Accession
  refseq_ncrna_accession: RefSeq ncRNA Accession
  refseq_nucleotide_gi: RefSeq Nucleotide GI
  refseq_protein_accession: RefSeq Protein Accession
  refseq_protein_gi: RefSeq Protein GI
  rfam_id: Rfam ID
  rgd_id: RGD ID
  sgd_id: SGD ID
  smart_id: SMART ID
  string_protein_interactor: STRING Protein Interactor
  tair_id: TAIR ID
  taxon_id: Taxon ID
  tcdb_id: TCDB ID
  tigrfams_id: TIGRFAMs ID
  tuberculist_id: TubercuList ID
  ucsc_id: UCSC ID
  unigene_id: UniGene ID
  uniprot_accession: UniProt Accession
  uniprot_entry_name: UniProt Entry Name
  uniprot_info: UniProt Info
  uniprot_protein_name: UniProt Protein Name
  unists_id: UniSTS ID
  vectorbase_gene_id: VectorBase Gene ID
  vega_gene_id: VEGA Gene ID
  vega_protein_id: VEGA Protein ID
  vega_transcript_id: VEGA Transcript ID
  wormbase_gene_id: WormBase Gene ID
  wormpep_protein_id: WormPep Protein ID
  xenbase_gene_id: XenBase Gene ID
  zfin_id: ZFIN ID