biodbnet:
  enabled: false
  endpoints:
    db2db:
      enabled: false
      params:
        input: "genesymbol"
        outputs: ["taxonid", "genesymbol", "affyid", "go-biologicalprocess"]
    getpathways:
      enabled: true
      params:
        pathways: "1"
biogrid:
  enabled: true
  endpoints:
    interactions:
      enabled: true
brenda:
  enabled: false
  endpoints:
    getKmValue:
      enabled: true
    getIc50Value:
      enabled: true
    getKcatKmValue:
      enabled: true
    getKiValue:
      enabled: true
    getPhRange:
      enabled: true
    getPhOptimum:
      enabled: true
    getPhStability:
      enabled: true
    getCofactor:
      enabled: true
    getTemperatureOptimum:
      enabled: true
    getTemperatureStability:
      enabled: true
    getTemperatureRange:
      enabled: true
chembl:
  enabled: false
  endpoints:
    activity:
      enabled: true
    binding_site:
      enabled: true
chebi:
  enabled: false
  endpoints:
    compounds:
      enabled: true
    ontology-children:
      enabled: true
    ontology-parents:
      enabled: true
genontology:
  enabled: false
  endpoints:
    bioentity-function:
      enabled: true
    ontology-term:
      enabled: true
interpro:
  enabled: false
  endpoints:
    entry:
      enabled: true
kegg:
  enabled: false
  endpoints:
    get:
      enabled: true
panther:
  enabled: false
  endpoints:
    familymsa:
      enabled: true
    geneinfo:
      enabled: true
pathwaycommons:
  enabled: false
  endpoints:
    fetch:
      enabled: true
      params:
        pattern: ["interacts-with", "used-to-produce"]
    top_pathways:
      enabled: true
      params:
        datasource: ["reactome", "uniprot"]
    neighborhood:
      enabled: true
      params:
        datasource: ["reactome", "uniprot"]
        pattern: ["interacts-with", "used-to-produce"]
        subpw: true
        direction: "undirected"
        limit: 1
pdb:
  enabled: false
  endpoints:
    entry:
      enabled: true
pubchem:
  enabled: false
  endpoints:
    protein:
      enabled: true
      options:
        concise:
          enabled: true
        summary:
          enabled: true
reactome:
  enabled: false
  endpoints:
    data-discover:
      enabled: true
rhea:
  enabled: false
  endpoints:
    rhea:
      enabled: true
refseq:
  enabled: false
  endpoints:
    protein:
      enabled: true
string:
  enabled: false
  endpoints:
    interaction_partners:
      enabled: true
    get_string_ids:
      enabled: true