get_string_ids:
  query_index: queryIndex
  query_item: queryItem
  str_id: stringId

interaction_partners:
  id_a: stringId_A
  id_b: stringId_B
  name_a: preferredName_A
  name_b: preferredName_B
  score: score
  nscore: nscore
  fscore: fscore
  pscore: pscore
  ascore: ascore
  escore: escore
  dscore: dscore
  tscore: tscore