#!/bin/bash

activities=(
    ace-inhibitor
    activating-ubiquitin-mediated-proteolysis
    alpha-amylase-inhibitor
    alpha-glucosidase-inhibitor
    anorectic
    antiamnestic
    antiangiogenic
    antiantifreeze
    antibacterial
    antibiofilm
    anticancer
    anticoronavirus
    antidiabetic
    antiendotoxin
    antifungal
    antihiv
    antihypertensive
    antiinflammatory
    antileishmania
    antimicrobial
    anti-MRSA
    anti-neurotensive
    antioncogenic
    antioxidative
    antiparasitic
    antiplasmodial
    antiprotozoal
    antithrombotic
    antitoxin
    antitrypanosomic
    antituberculosis
    antitumor
    antiviral
    anuran-defense
    bacterial-permease-ligand
    binding
    Blood-Brain-Barrier
    calpain-2-inhibitor
    camkii-inhibitor
    campde-inhibitor
    celiac-toxic
    cell-cell-comunication
    cell-penetrating
    chemotactic
    contracting
    cytokine-growth-factor
    cytotoxic
    dipeptidyl-peptidase-iii-inhibitor
    dipeptidyl-peptidaseiv
    drug-delivery
    edema-inducer
    embryotoxic
    hemolytic
    heparin-binding
    hmg-coa-reductase-inhibitor
    hypocholesterolemic
    hypolipidemic
    hypotensive
    immunomodulating
    immunostimulating
    inhibitor
    insecticidal
    membrane-active-peptide
    natriuretic
    neuroactive
    neuropeptide
    opioid-agonist
    opioid-antagonist
    opioid
    orphan-receptor-gpr14-agonist
    peptide-hormones
    polystyrene-surface-binding
    protease-inhibitor
    protein-kinase-c-inhibitor
    quorum-sensing
    regulating
    renin-inhibitor
    stimulating
    surface-binding
    targeting-GN
    targeting-GP
    targeting-GV
    targeting-mammals
    toxicology
    trypsin-inhibitory
    tumor-homing
    uterotonic
    vasoconstrictor
    wound-healing
)

# Download each activity file
for activity in "${activities[@]}"; do
    python src/uniprot_search_query.py \
        -q "$activity AND reviewed:true" \
        -o "uniprot_search/uniprot_${activity}.csv"
    sleep 5
done