fetch:
  id: id
  name: name
  db: db
  cellular_location: cellularLocation
  chemical_formula: chemicalFormula
  comment: comment
  component: component
  component_stoichiometry: componentStoichiometry
  data_source: dataSource
  display_name: displayName
  entity_feature: entityFeature
  entity_reference: entityReference
  feature: feature
  feature_location: featureLocation
  id_version: idVersion
  imports: imports
  member_entity_reference: memberEntityReference
  member_physical_entity: memberPhysicalEntity
  modification_type: modificationType
  molecular_weight: molecularWeight
  organism: organism
  physical_entity: physicalEntity
  position_status: positionStatus
  relationship_type: relationshipType
  sequence_interval_begin: sequenceIntervalBegin
  sequence_interval_end: sequenceIntervalEnd
  sequence_position: sequencePosition
  standard_name: standardName
  stoichiometric_coefficient: stoichiometricCoefficient
  structure: structure
  structure_data: structureData
  structure_format: structureFormat
  term: term
  xref: xref
top_pathways:
  uri: uri
  biopax_class: biopaxClass
  name: name
  data_source: dataSource
  organism: organism
  pathway: pathway
  excerpt: excerpt
  num_participants: numParticipants
  num_processes: numProcesses
neighborhood:
  id: id
  name: name
  db: db
  cellular_location: cellularLocation
  chemical_formula: chemicalFormula
  comment: comment
  component: component
  component_stoichiometry: componentStoichiometry
  control_type: controlType
  controlled: controlled
  controller: controller
  conversion_direction: conversionDirection
  data_source: dataSource
  display_name: displayName
  ec_number: eCNumber
  entity_feature: entityFeature
  entity_reference: entityReference
  feature: feature
  feature_location: featureLocation
  id_version: idVersion
  imports: imports
  left: left
  member_entity_reference: memberEntityReference
  member_physical_entity: memberPhysicalEntity
  modification_type: modificationType
  molecular_weight: molecularWeight
  organism: organism
  physical_entity: physicalEntity
  position_status: positionStatus
  relationship_type: relationshipType
  right: right
  sequence_interval_begin: sequenceIntervalBegin
  sequence_interval_end: sequenceIntervalEnd
  sequence_position: sequencePosition
  source: source
  standard_name: standardName
  stoichiometric_coefficient: stoichiometricCoefficient
  structure: structure
  structure_data: structureData
  structure_format: structureFormat
  term: term
  title: title
  url: url
  xref: xref
  year: year