entry:
  accession: proteins.accession
  length: proteins.protein_length
  organism_id: proteins.organism.id
  protein_source_db: proteins.source_database
  in_alphafold: proteins.in_alphafold
  interpro_accession: metadata.accession
  name: metadata.name
  type: metadata.type
  source_database: metadata.source_database
  integrated: metadata.integrated
  pfam: metadata.member_databases.pfam
  prosite: metadata.member_databases.prosite
  smart: metadata.member_databases.smart
  prints: metadata.member_databases.prints
  panther: metadata.member_databases.panther
  cathgene3d: metadata.member_databases.cathgene3d
  ssf: metadata.member_databases.ssf
  go_identifier: metadata.go_terms.identifier
  go_name: metadata.go_terms.name
  go_category: metadata.go_terms.category.name
  locations: proteins.entry_protein_locations